<?php
/**
 * Copyright © 2015 PlazaThemes.com. All rights reserved.

 * @author PlazaThemes Team <contact@plazathemes.com>
 */
?>
<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Plazathemes\Blog\Block\Sidebar\Recent
 */
?>

<?php
	$enable = $this->getConfig('enable_frontend');
	$auto = $this->getConfig('auto');
	$speed = $this->getConfig('speed');
	$default = $this->getConfig('default');
	$desktop = $this->getConfig('desktop');
	$desktop_small = $this->getConfig('desktop_small');
	$tablet = $this->getConfig('tablet');
	$mobile = $this->getConfig('mobile');
	$pagination = $this->getConfig('pagination');
	$show_next_back = $this->getConfig('show_next_back');
	$show_navigation_control = $this->getConfig('show_navigation_control');
	$title = $this->getConfig('title');
	if($show_next_back)
		$show_next_back = 'true';
	else
		$show_next_back = 'false';
	$show_navigation_control = $this->getConfig('show_navigation_control');
	if($show_navigation_control)
		$show_navigation_control = 'true';
	else
		$show_navigation_control = 'false';
	$_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count() && $enable) { ?>
<section class="widget block-recent-posts space-modul border-box" data-bind="scope: 'recemt-posts'">
	<div class=""> 
		<header class="title1">
			<h2><?php echo __($title) ?></h2>
		</header>
		<div class="owl-container">
			<div class="block-content">
				<div class="ptowl">
					<?php foreach ($_postCollection as $_post) { ?>
						<div class="item">
							<div class="item-inner">
								<div class="blog-image">
									<a href="<?php echo $_post->getPostUrl() ?>">
										<img src="<?php echo $this->getMediaFolder().$_post->getThumbnailimage() ?>" alt="<?php echo $block->escapeHtml($_post->getTitle()) ?>"/>
									</a> 
								</div>
								<div class="blog-content"> 
									<div class="blog-content-inner">
										 <h3 class="blog-title"><a href="<?php echo $_post->getPostUrl() ?>"><?php echo $block->escapeHtml($_post->getTitle()) ?></a></h3> 	
										<div class="time-comment">
											<?php 
												$date = $_post->getPublishTime();
											?>
											<span class="date-time"><span class="date"><?php echo __(date("d", strtotime($date))) ?></span><span class="month"><?php echo __(date(" M", strtotime($date))) ?></span></span>
											<span class="comment"><fb:comments-count href="<?php echo $_post->getPostUrl() ?>"></fb:comments-count> comments </span>
										</div>
										
										<p class="short-des"><?php echo $_post->getShortContent() ?></p> 
										<a class="readmore" href="<?php echo $_post->getPostUrl() ?>">
											<?php echo __('Read more') ?>
										</a>
									</div>
								</div>
							</div>
						</div>
					<?php } ?>
				</div>
			</div>
		</div>
    </div>
</section>
<script type="text/javascript">
	require(["jquery","owlcarousel/minjs"], function($,owlCarousel){
		$(document).ready(function(){
			$(".block-recent-posts .ptowl").owlCarousel({
				<?php
					if(($auto== 'true') && $speed):
				?>
				autoPlay : <?php echo $speed; ?>,
				<?php
					endif;
				?>
				items : <?php echo $default; ?>,
				itemsDesktop : [1199,<?php echo $desktop; ?>],
				itemsDesktopSmall : [980,<?php echo $desktop_small; ?>],
				itemsTablet: [768,<?php echo $tablet; ?>],
				itemsMobile : [479,<?php echo $mobile; ?>],
				slideSpeed : <?php echo $pagination; ?>,
				paginationSpeed : <?php echo $pagination; ?>,
				rewindSpeed : <?php echo $pagination; ?>,
				addClassActive: true,
				navigation : <?php echo $show_next_back; ?>,
				stopOnHover : true,
				pagination : <?php echo $show_navigation_control; ?>,
				scrollPerPage:true,
				addClassActive: true, 
				afterAction: function(el){
			       	this.$owlItems.removeClass('last-active');
			        this.$owlItems .eq(this.currentItem + (this.owl.visibleItems.length - 1)).addClass('last-active');
			        this.$owlItems.removeClass('first-active');
			        this.$owlItems .eq(this.currentItem).addClass('first-active');  
			    } 
			});
		});
	});
</script>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.11&appId=329434857489559';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script> 
<?php } ?>