<?php 
	$enable = $block->getConfig('enabled');
	if($enable < 1) return ; 
	$items = $block->getConfig('items');
	$speed = $block->getConfig('speed');
	$qty = $block->getConfig('qty');
	$showCart = $block->getConfig('addtocart');
	$showWishlist = $block->getConfig('wishlist');
	$showCompare = $block->getConfig('compare');
	$show_navigation = $block->getConfig('navigation');
	$show_pagination = $block->getConfig('pagination');
	$auto = $block->getConfig('auto');
	$rows = 1;
	$title = $block->getTitle(); 
	$identify = trim($block->getIdentify()); 
	$categoryIds = $block->getCategoryIds();
	$categoryIds = explode(',', $categoryIds);

	$productsOnRow = 2 ;
	if(!$productsOnRow) $productsOnRow = 3;

?>

<div class="categorytab-container">
<header class='title-container'>
	<div class="title1">
		<?php 	echo '<h2>'.$title.'</h2>'; ?>
	</div>
	
	<ul class="tabs tabs<?php echo '-'.$identify;?>"> 
   <?php 
	$k = 0;
	foreach($categoryIds as $cate_id) {
		$cate_model =  $block->getCategory($cate_id);
		$cateName = $cate_model->load($cate_id)->getName();
		//echo "<pre>"; print_r($cate_model->getData()); die; 
		if($cateName) {
   ?>
			<li class="<?php if($k==0){ echo "active"; }?>" rel="tab<?php echo $cate_id.'-'.$identify;?>"><?php  echo $cateName; ?></li>
	<?php }  $k++; } ?>
    </ul>
</header>

    <?php 
		
		$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
		$image = 'new_products_content_widget_grid';
		$type = 'widget-new-grid';
		$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
		$showWishlist = true;
		$showCompare = true;
		$showCart = true;
	?>
	<div class="tab_container"> 
		<?php foreach($categoryIds as $cate_id) { ?>
		<div id="tab<?php echo $cate_id.'-'.$identify;?>" class="tab_content_<?php echo $identify; ?>">  	
			<div class="category_tab_slider">
				<?php 
				$newItems =  $block -> getProductCate($cate_id)->getItems(); 
				$i=0;
				foreach($newItems as $_item) { 
					$productImage = $block->getImage($_item, $image);
				?>
				<?php if($i++%$rows==0) { ?> <div class="product_row"> <?php } ?>
					<div class="item">
						<div class="item-inner">
							<div class="image-container">
								<?php
									$newFromDate = $_item->getNewsFromDate();
									$newToDate = $_item->getNewsToDate();                
									$now = date("Y-m-d H:m:s");
									// Get the Special Price
									$specialprice = $_item->getSpecialPrice(); 
									// Get the Special Price FROM date
									$specialPriceFromDate = $_item->getSpecialFromDate();
									// Get the Special Price TO date
									$specialPriceToDate = $_item->getSpecialToDate();
									// Get Current date
								   if ($specialprice&&(($specialPriceFromDate <= $now && $specialPriceToDate >= $now) || (($specialPriceFromDate <= $now && $specialPriceFromDate != NULL) && $specialPriceToDate  == ''))){
									$_savePercent = 100 - round(($_item->getSpecialPrice() / $_item->getPrice())*100);
									echo "<span class='sale'>-".$_savePercent."%</span>";
								   }

								   if((($newFromDate <= $now && $newToDate >= $now) || (($newFromDate <= $now && $newFromDate != NULL) && $newToDate == NULL))) {
								   ?>
								   <span class="new"><?php echo __('new') ?></span>
								   <?php
								   } 
								?>
								<a href="<?php echo $block->getProductUrl($_item) ?>" class="product-item-photo">
									<?php echo $productImage->toHtml() ?>
								</a>
								<?php if ($showWishlist): ?> 
									<div class="wishlist-inner">
										<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
											<a href="#"
											   data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'
											   class="action towishlist" data-action="add-to-wishlist"
											   title="<?php echo __('Add to Wishlist') ?>">
												<span><?php echo __('Wishlist') ?></span>
											</a>
										<?php endif; ?>  
									</div> 
								<?php endif; ?>  
							</div>
							<div class="box-info"> 
								<h2 class="product-item-name">
									<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
									   href="<?php echo $block->getProductUrl($_item) ?>"
									   class="product-item-link">
										<?php echo $block->escapeHtml($_item->getName()) ?>
									</a>
								</h2>
								<?php if ($templateType): ?>
									<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true); ?>
								<?php endif; ?>
								<div class="item-price">
									<?php
										echo $block->getProductPrice($_item);
									?>
								</div>
								<?php if ( $showCompare || $showCart): ?>
									<div class="box-hover">
										<div class="add-to-links" data-role="add-to-links">   
											<div class="actions-primary">
												<?php if ($_item->isSaleable()): ?>
													<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
														<button class="action tocart primary"
																data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getAddToCartUrl($_item) ?>"}}'
																type="button" title="<?php echo __('Add to Cart') ?>">
															<span><?php echo __('Add to Cart') ?></span>
														</button>
													<?php else: ?>
														<?php
															$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
															$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
														?>
														<button class="action tocart primary"
																data-post='<?php echo $postData; ?>'
																type="button" title="<?php echo __('Add to Cart') ?>">
															<span><?php echo __('Add to Cart') ?></span>
														</button>
													<?php endif; ?>
												<?php else: ?>
													<?php if ($_item->getIsSalable()): ?>
														<div class="stock available"><span><?php echo __('In stock') ?></span></div>
													<?php else: ?>
														<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
											</div> 
											<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
												<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
												<a href="#" class="action tocompare"
												   data-post='<?php echo $compareHelper->getPostDataParams($_item);?>'
												   title="<?php echo __('Add to Compare') ?>">
													<span><?php echo __('Compare') ?></span>
												</a>
											<?php endif; ?>
										</div>
									</div>
								<?php endif; ?>  
							</div>
						</div>
					</div>
						<?php if($i%$rows==0 || $i == count($newItems)) { ?> </div> <?php }?>
				<?php 
				}
				?>
			</div> 
			
		 </div><!-- #tab1 -->
		 <?php }?>

		 
	 </div> <!-- .tab_container --> 
</div>
<script type="text/javascript">
require(["jquery","slick"], function($,slick){

	$(document).ready(function(){
		$(".tab_content_<?php echo $identify; ?>").hide();
		$(".tab_content_<?php echo $identify; ?>:first").show(); 

		$("ul.tabs<?php echo '-'.$identify;?> li").click(function() {
			$("ul.tabs<?php echo '-'.$identify;?> li").removeClass("active");
			$(this).addClass("active");
			$(".tab_content_<?php echo $identify; ?>").hide();
			var activeTab = $(this).attr("rel"); 
			$("#"+activeTab).fadeIn(); 
		});
		
		 // products carousel vertical
		$('.tab_content_<?php echo $identify; ?> .category_tab_slider').slick({
		    autoplay: true,
		    arrows: false,
		    dots: false,
		    slidesToShow: 3, 
		    draggable: false,
		    infinite: true,
		    pauseOnHover: false,
		    swipe: false,
		    touchMove: false,
		    vertical: true,
		    speed: <?php if($speed) echo $speed; else echo '500'; ?>,
		    autoplaySpeed: 2000, 
		    responsive: [ 
				{
				  breakpoint: 1200,
				  settings: {
					slidesToShow: 3,
					slidesToScroll: 1
				  }
				},
				{
				  breakpoint: 992,
				  settings: {
				  	vertical: false,
					slidesToShow: 3,
					slidesToScroll: 1
				  }
				},
				{
				  breakpoint: 768,
				  settings: {
				  	vertical: false,
					slidesToShow: 2,
					slidesToScroll: 1
				  }
				},
				{
				  breakpoint: 480,
				  settings: {
				  	vertical: false,
					slidesToShow: 1,
					slidesToScroll: 1
				  }
				}
			]
		}); 
	});
	
});
 

</script> 
