<div class="pt_categorytop catlist space-modul">
	<div class="container">
		<div class="title1"><h2><?php echo 'FEATURED CATEGORIES'; ?></h2> <p><?php echo 'Mirum est notare quam littera gothica quam nunc putamus parum claram.'; ?></p></div>
		<div class="pt-categorytop-inner"> 
			<?php
			$catListTop = $block->getCatListTop();
			$i = 0;
			$last = count($catListTop);
			foreach ($catListTop as $catTop) {
				//echo "<pre>"; print_r($catTop->getData()); echo "</pre>"; 
				$thumb_url = $block -> getThumbUrl($catTop->getThumbPopular());
				if($i < $last){
					echo '<div class="catgrid">';
				}else {
					echo '<div class="catgridlast">';
				}
				$link = $block->getCategoryLink($catTop);
						echo '<div class="catlist_level_top item"> 
									<div class="catlist-content">
									<div class="cat-images"><a href="'.$link.'">' 
										.'<img src="'.$thumb_url.'" alt="'.$catTop->getName().'" />
									</a></div>';
						$CatList = $block->getCatByPath((int) $catTop->getId(), $catTop->getPath());
						$j = 0;
						echo '<div class="sub-inner"><h3>'.$catTop->getName().'</h3><ul>';
							foreach ($CatList as $cat) {
								$link_child = $block->getCategoryLink($cat);
							  if($j >= 5) break;
								echo '<li><a href="'.$link_child.'">'.$cat->getName().'</a></li>';
								$j++;
							}
							echo '<li class="link-category"><a href="'.$link.'">See more</a></li>';
						echo '</ul></div></div></div></div>';
				$j++; 
			}
			?> 
		</div>
	</div>
</div>
<script type="text/javascript">
	require(["jquery","owlcarousel/minjs"], function($,owlCarousel){
		$(document).ready(function(){
			$(".pt_categorytop .pt-categorytop-inner").owlCarousel({ 
				items : 7,
				itemsDesktop : [1199,6],
				itemsDesktopSmall : [980,5],
				itemsTablet: [768,4],
				itemsMobile : [479,2],
				pagination: false,
				navigation: true,
				addClassActive: true, 
				afterAction: function(el){
			       	this.$owlItems.removeClass('last-active');
			        this.$owlItems .eq(this.currentItem + (this.owl.visibleItems.length - 1)).addClass('last-active');
			        this.$owlItems.removeClass('first-active');
			        this.$owlItems .eq(this.currentItem).addClass('first-active');  
			    } 
			});
		});
	});
</script>