	<?php 
		$enable = $block->getConfig('enabled');
		if($enable < 1) return ; 
		$items = $block->getConfig('items');
		$speed = $block->getConfig('speed');
		$qty = $block->getConfig('qty');
		$showCart = $block->getConfig('addtocart');
		$showWishlist = $block->getConfig('wishlist');
		$showCompare = $block->getConfig('compare');
		$show_navigation = $block->getConfig('navigation');
		$show_pagination = $block->getConfig('pagination');
		$auto = $block->getConfig('auto');
		$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
		$image = 'new_products_content_widget_grid';
		$type = 'widget-new-grid';
		$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
		$rows = $block->getConfig('row');
	?>
<div class="producttab-container space-modul quickview-box border-box">	
<div class="title-tab">
	<ul class="tabs">
		<?php 
			$tab_contents = $block->getTabContent() ; 
	    $count=0;			
		foreach($tab_contents as $tab) {
			?>
		<li rel="tab_<?php echo $tab['id'];?>"  <?php if ($count==0) ?> class="active" > <?php echo $tab['name'];?></li>
			<?php
			$count ++; 
		}
		?>
	</ul>
</div>	
	<div class="tab_container"> 
	   <?php 
		foreach($tab_contents as $tab) {
		?>
		<div class="owl-container">
		 <div id="tab_<?php echo $tab['id'];?>" class="tab_content"> 
		 	<div class="productTabContent owl-carousel">
						<?php 
							$i=0;
							$productItems =  $tab['productInfo']; 
							foreach($productItems as $_item) { 
									$productImage = $block->getImage($_item, $image);
							?>
								<?php if($i++%$rows==0) { ?> <div class="product_row"> <?php } ?>
								
								<div class="item">
									<div class="item-inner">
										<div class="image-container">
											<?php
												$newFromDate = $_item->getNewsFromDate();
												$newToDate = $_item->getNewsToDate();                
												$now = date("Y-m-d H:m:s");
												// Get the Special Price
												$specialprice = $_item->getSpecialPrice(); 
												// Get the Special Price FROM date
												$specialPriceFromDate = $_item->getSpecialFromDate();
												// Get the Special Price TO date
												$specialPriceToDate = $_item->getSpecialToDate();
												// Get Current date
											   if ($specialprice&&(($specialPriceFromDate <= $now && $specialPriceToDate >= $now) || (($specialPriceFromDate <= $now && $specialPriceFromDate != NULL) && $specialPriceToDate  == ''))){
												$_savePercent = 100 - round(($_item->getSpecialPrice() / $_item->getPrice())*100);
												echo "<span class='sale'>-".$_savePercent."%</span>";
											   } 

											   if((($newFromDate <= $now && $newToDate >= $now) || (($newFromDate <= $now && $newFromDate != NULL) && $newToDate == NULL))) {
											   ?>
											   <span class="new"><?php echo __('new') ?></span>
											   <?php
											   } 
											?>
											<a href="<?php echo $block->getProductUrl($_item) ?>" class="product-item-photo">
											<?php echo $productImage->toHtml() ?>
											</a> 
											<?php if ($showWishlist): ?> 
												<div class="wishlist-inner">
													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
														<a href="#"
														   data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'
														   class="action towishlist" data-action="add-to-wishlist"
														   title="<?php echo __('Add to Wishlist') ?>">
															<span><?php echo __('Wishlist') ?></span>
														</a>
													<?php endif; ?>  
												</div> 
											<?php endif; ?>   
										</div>
										<div class="box-info">  
											<h2 class="product-item-name">
												<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
												   href="<?php echo $block->getProductUrl($_item) ?>"
												   class="product-item-link">
													<?php echo $block->escapeHtml($_item->getName()) ?>
												</a>
											</h2>
											<?php if ($templateType): ?>
												<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true); ?> 
											<?php endif; ?>
											<div class="item-price">
												<?php
													echo $block->getProductPrice($_item);
												?> 
											</div>  
											<?php if ( $showCompare || $showCart): ?>
												<div class="box-hover">
													<div class="add-to-links" data-role="add-to-links">   
														<div class="actions-primary">
															<?php if ($_item->isSaleable()): ?>
																<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
																	<button class="action tocart primary"
																			data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getAddToCartUrl($_item) ?>"}}'
																			type="button" title="<?php echo __('Add to Cart') ?>">
																		<span><?php echo __('Add to Cart') ?></span>
																	</button>
																<?php else: ?>
																	<?php
																		$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
																		$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
																	?>
																	<button class="action tocart primary"
																			data-post='<?php echo $postData; ?>'
																			type="button" title="<?php echo __('Add to Cart') ?>">
																		<span><?php echo __('Add to Cart') ?></span>
																	</button>
																<?php endif; ?>
															<?php else: ?>
																<?php if ($_item->getIsSalable()): ?>
																	<div class="stock available"><span><?php echo __('In stock') ?></span></div>
																<?php else: ?>
																	<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
																<?php endif; ?>
															<?php endif; ?>
														</div> 
														<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
															<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
															<a href="#" class="action tocompare"
															   data-post='<?php echo $compareHelper->getPostDataParams($_item);?>'
															   title="<?php echo __('Add to Compare') ?>">
																<span><?php echo __('Compare') ?></span>
															</a>
														<?php endif; ?>
													</div>
												</div>
											<?php endif; ?> 
										</div>
									</div>	
								</div>
								
								 <?php if($i%$rows==0 || $i == count($productItems)) { ?> </div> <?php }?>
							<?php 
							}
							?>
					</div>
					</div>
		</div> 
		<?php 
		} 
		?>
	</div>
</div>
	
<script type="text/javascript">
	require(["jquery","owlcarousel/minjs"], function($,owlCarousel){
	$(".producttab-container .tab_content").hide();
	$(".producttab-container .tab_content:first").show(); 
	$(".producttab-container ul.tabs li").removeClass("active");
	$(".producttab-container ul.tabs li:first-child").addClass("active");
	$(".producttab-container ul.tabs li").click(function() {
		$(".producttab-container ul.tabs li").removeClass("active");
		$(this).addClass("active");
		$(".producttab-container .tab_content").hide();
		$(".producttab-container .tab_content").removeClass("animate1");
		var activeTab = $(this).attr("rel"); 
		$("#"+activeTab) .addClass("animate1");
		$("#"+activeTab).fadeIn(); 
	});
	  $(".productTabContent").owlCarousel({
	    		items : <?php if($items) { echo $items; } else { echo 4; }?>,
				autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
				slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				navigation : <?php if($show_navigation) echo 'true'; else echo 'false'; ?>,
				stopOnHover : true,
				pagination : <?php if($show_pagination) echo 'true'; else echo 'false'; ?>,
				itemsDesktop : [1199,4],
				itemsDesktopSmall : [992,3],
				itemsTablet: [767,2],
				itemsMobile : [480,1],
				addClassActive: true,
				afterAction: function(el){
			       	this.$owlItems.removeClass('last-active');
			        this.$owlItems .eq(this.currentItem + (this.owl.visibleItems.length - 1)).addClass('last-active');
			        this.$owlItems.removeClass('first-active');
			        this.$owlItems .eq(this.currentItem).addClass('first-active');  
			    }
	});
	

});

</script> 

 

